add_rules("mode.debug", "mode.release", "plugin.compile_commands.autoupdate")
set_languages("cxx20")
add_requires("cpp-httplib", "nlohmann_json")

target("db_explorer")
    set_kind("binary")
    add_files("src/db_explorer/*.cpp")
    add_includedirs(".deps\\wcdb\\src\\build\\export_headers")
    add_includedirs(".deps\\wcdb\\sqlcipher\\include\\sqlcipher")
    add_includedirs(".deps\\wcdb\\zstd\\lib")
    add_linkdirs(".deps\\wcdb\\src\\build\\Release")
    add_packages("cpp-httplib", "nlohmann_json")
    add_links("sqlcipher", "WCDB", "zstd")
    add_syslinks("Crypt32", "Ws2_32")
    add_defines("SQLITE_HAS_CODEC=1", "SQLITE_ENABLE_MEMORY_MANAGEMENT=1", "SQLITE_DEFAULT_FILE_FORMAT=4", "SQLITE_UNTESTABLE")
    add_cxflags("/wd4068")
    after_build(function (target)
        os.cp(".deps\\wcdb\\src\\build\\Release\\WCDB.dll", target:targetdir())
        local webdir = path.join(target:targetdir(), "web")
        os.mkdir(webdir)
        os.cp(path.join("web", "index.html"), webdir)
    end)
